name: Build and Deploy Docs
on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - src/**
      - .umirc.ts
      - .github/**
      - package.json

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Build docs
        run: pnpm run doc
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_WORKFLOW }}
          BRANCH: gh-pages
          FOLDER: docs-dist
